//Auth Action Types
export const LOGIN = "LOGIN";
export const SEND_VERIFICATION_CODE = "SEND_VERIFICATION_CODE";
export const MATCH_VERIFICATION_CODE = "MATCH_VERIFICATION_CODE";
export const SIGNUP_CREDENTIONALS = "SIGNUP_CREDENTIONALS";
export const SIGNUP_PROFILE = "SIGNUP_PROFILE";
export const RESET_PASSWORD_EMAIL = "RESET_PASSWORD_EMAIL";
export const RESET_PASSWORD_CODE_VERIFICATION =
  "RESET_PASSWORD_CODE_VERIFICATION";
export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";

//Meal_MenuAction Types
export const SHOW_ALL_MEALS_TO_BUYER = "SHOW_ALL_MEALS_TO_BUYER";
export const SHOW_BREAKFAST_MEALS_TO_BUYER = "SHOW_BREAKFAST_MEALS_TO_BUYER";
export const SHOW_LUNCH_MEALS_TO_BUYER = "SHOW_LUNCH_MEALS_TO_BUYER";
export const SHOW_DINNER_MEALS_TO_BUYER = "SHOW_DINNER_MEALS_TO_BUYER";
export const SHOW_SPECIFIC_SELLER_MEALS_TO_BUYER =
  "SHOW_SPECIFIC_SELLER_MEALS_TO_BUYER";
export const SHOW_SPECIFIC_SELLER_MENUS_TO_BUYER =
  "SHOW_SPECIFIC_SELLER_MENUS_TO_BUYER";

//Cart Action Types
export const ADD_TO_CART_BUYER = "ADD_TO_CART_BUYER";
export const SHOW_CART_OF_BUYER = "SHOW_CART_OF_BUYER";
export const DELETE_TO_CART_BUYER = "DELETE_TO_CART_BUYER";
export const INCRIMENT_PRODUCT_CART = "INCRIMENT_PRODUCT_CART";
export const DECRIMEMT_PRODUCT_CART = "DECRIMEMT_PRODUCT_CART";
export const DELETE_COMPLETE_BUYER_CART = "DELETE_COMPLETE_BUYER_CART";
export const ODERLINE_PREPARE = "ODERLINE_PREPARE";

//Cart Action Types
export const PLACE_ORDER = "PLACE_ORDER";
//SearchSellerAndMeal
export const SEARCH_SELLER = "SEARCH_SELLER";

//Order HistoryBuyer
export const BUYER_ORDER_HISTORY = "BUYER_ORDER_HISTORY";

//BuyerProfile
export const SHOW_BUYER_PROFILE = "SHOW_BUYER_PROFILE";
export const UPDATE_BUYER_PROFILE = "UPDATE_BUYER_PROFILE";

//BroadCast
export const BROADCAST_LIST_OF_MENUS = "BROADCAST_LIST_OF_MENUS";
export const SHOW_INTREST_AGAINST_BROADCAST = "SHOW_INTREST_AGAINST_BROADCAST";
export const SHOW_LIST_OF_NEEDED_CONFIRMATION =
  "SHOW_LIST_OF_NEEDED_CONFIRMATION";
//ORDER
export const BOOKED_ORDER_BUYER = "BOOKED_ORDER_BUYER";
export const DELIVERED_ORDER_BUYER = "DELIVERED_ORDER_BUYER";

//VoucherCode Match
export const MATCH_VOUCHER_CODE = "MATCH_VOUCHER_CODE";
