//PATNER TO BUYER NOTIFICATION TYPES
export const SEND_BROADCAST_FROM_PATNER_TO_BUYER =
  "SEND_BROADCAST_FROM_PATNER_TO_BUYER";

export const ASK_FOR_CONFIRMATION_FROM_BUYERS_BY_PATNER =
  "ASK_FOR_CONFIRMATION_FROM_BUYERS_BY_PATNER";
