//Auth Action Types
export const LOGIN = "LOGIN";
export const SEND_VERIFICATION_CODE = "SEND_VERIFICATION_CODE";
export const MATCH_VERIFICATION_CODE = "MATCH_VERIFICATION_CODE";
export const SIGNUP_CREDENTIONALS = "SIGNUP_CREDENTIONALS";
export const SIGNUP_PROFILE = "SIGNUP_PROFILE";
export const RESET_PASSWORD_EMAIL = "RESET_PASSWORD_EMAIL";
export const RESET_PASSWORD_CODE_VERIFICATION =
  "RESET_PASSWORD_CODE_VERIFICATION";
export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";

export const SHOW_PATNER_PROFILE = "SHOW_PATNER_PROFILE";
export const UPDATE_PATNER_PROFILE = "UPDATE_PATNER_PROFILE";
//AllSellerShow
export const SHOW_ALL_SELLER_TO_PATNER = "SHOW_ALL_SELLER_TO_PATNER";

//BroadCast
export const SEND_BROADCAST_TO_BUYER = "SEND_BROADCAST_TO_BUYER";
export const WAITING_BROADCAST = "WAITING_BROADCAST";
export const ASKING_FOR_CONFIRMATION = "ASKING_FOR_CONFIRMATION";
//SellerConnection
export const SHOW_REQUESTS_OF_SELLERS = "SHOW_REQUESTS_OF_SELLERS";
export const ACCEPT_REJECT_SELLER_REQUEST = "ACCEPT_REJECT_SELLER_REQUEST";
export const ACCPTED_SELLER_LIST = "ACCPTED_SELLER_LIST";
