//Auth Action Types
export const LOGIN = "LOGIN";
export const SEND_VERIFICATION_CODE = "SEND_VERIFICATION_CODE";
export const MATCH_VERIFICATION_CODE = "MATCH_VERIFICATION_CODE";
export const SIGNUP_CREDENTIONALS = "SIGNUP_CREDENTIONALS";
export const SIGNUP_PROFILE = "SIGNUP_PROFILE";
export const RESET_PASSWORD_EMAIL = "RESET_PASSWORD_EMAIL";
export const RESET_PASSWORD_CODE_VERIFICATION =
  "RESET_PASSWORD_CODE_VERIFICATION";
export const ALL_SELLER_TYPE = "ALL_SELLER_TYPE";
export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";
export const SHOW_SELLER_PROFILE = "SHOW_SELLER_PROFILE";
export const UPDATE_SELLER_PROFILE = "UPDATE_SELLER_PROFILE";
//Menu Action Types
export const ADD_MENU = "ADD_MENU";
export const SHOW_MENU = "SHOW_MENU";
export const UPDATE_MENU = "UPDATE_MENU";
export const DELETE_MENU = "DELETE_MENU";

//Meal Action Types
export const ADD_MEAL = "ADD_MEAL";
export const UPDATE_MEAL = "UPDATE_MEAL";
export const DELETE_MEAL = "DELETE_MEAL";
export const SHOW_ALL_MEALS = "SHOW_ALL_MEALS";
export const SHOW_ALL_BREAKFAST = "SHOW_ALL_BREAKFAST";
export const SHOW_ALL_LUNCH = "SHOW_ALL_LUNCH";
export const SHOW_ALL_DINNER = "SHOW_ALL_DINNER";

//Order Action Types
export const SHOW_BOOKED_ORDERS_OF_BUYER = "SHOW_BOOKED_ORDERS_OF_BUYER";
export const SHOW_BOOKED_ORDERS_OF_PARTNER = "SHOW_BOOKED_ORDERS_OF_PARTNER";
export const SHOW_DELIVERED_ORDERS_OF_BUYER = "SHOW_DELIVERED_ORDERS_OF_BUYER";
export const SHOW_DELIVERED_ORDERS_OF_PARTNER =
  "SHOW_DELIVERED_ORDERS_OF_PARTNER";

export const DYNAMIC_ROUTE = "DYNAMIC_ROUTE";
//<MARK_ORDER_DELIVERED
export const ORDER_DELIVERED = "ORDER_DELIVERED";

//ASSOCIATED_PATNER
export const SHOW_ALL_PATNER_LIST = "SHOW_ALL_PATNER_LIST";
export const SEARCH_PATNER = "SEARCH_PATNER";
export const SEND_REQUEST_TO_PATNER = "SEND_REQUEST_TO_PATNER";

//CONNECTED PATNERS
export const CONNECTED_PARTNERS = "CONNECTED_PARTNERS";
